name: saloon_appointment_booking_system
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^6.2.1
    flutter_dotenv: ^5.2.1
    http: ^1.2.2
    image_picker: ^1.1.2
    image: ^4.2.0

    # secure storage
    flutter_secure_storage: ^9.2.4

    # state management packages
    get: ^4.6.6
    get_storage: ^2.1.1

    # firebase packages
    firebase_core: ^3.8.1
    firebase_auth: ^5.3.4
    cloud_firestore: ^5.6.0

    # onboarding packages
    animated_splash_screen: ^1.3.0
    lottie: ^3.1.3

    # svg adding package
    flutter_svg: ^2.0.16

    # carousel
    flutter_carousel_widget: ^3.1.0

    # generate a skeleton while fetching data
    skeletonizer: ^1.4.3

    # date picker
    easy_date_timeline: ^2.0.6


dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: ^0.14.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logos/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/logos/logo_foreground.png"

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/logos/
        - assets/icons/
        - assets/images/
        - assets/images/clients/
        - assets/images/empty_placeholder/
        - assets/animations/
